version: '3'
services:
  node:
    #image: node:lts-fermium
    build: ../
    #restart: always
    container_name: "msg-node"
    ports:
     - "9004:9004"
    #  - "443:443"
    volumes:
     - ../src:/home/src